# Generated by Django 4.1.7 on 2023-10-12 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='PhylloWebhookMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField(help_text='When the event was received')),
                ('payload', models.JSONField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sdk_token', models.CharField(max_length=250)),
                ('username', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddIndex(
            model_name='phyllowebhookmessage',
            index=models.Index(fields=['received_at'], name='creat0r_phy_receive_502b13_idx'),
        ),
    ]
