# Generated by Django 4.1.7 on 2023-10-17 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creat0r', '0002_platform_remove_account_platform_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='user',
        ),
        migrations.AddField(
            model_name='account',
            name='phyllo_account_id',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
