# Generated by Django 4.1.7 on 2023-10-23 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creat0r', '0004_platform_followers_platform_likes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platform',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='platform',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='platform',
            name='phyllo_profile_id',
        ),
        migrations.RemoveField(
            model_name='platform',
            name='posts',
        ),
        migrations.RemoveField(
            model_name='platform',
            name='views',
        ),
        migrations.AddField(
            model_name='account',
            name='followers',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='likes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='phyllo_profile_id',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='posts',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='views',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
